/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecruitersRouteImport } from './routes/recruiters'
import { Route as PositionSummaryRouteImport } from './routes/position-summary'
import { Route as DailyReportingRouteImport } from './routes/daily-reporting'
import { Route as CandidatePipelineRouteImport } from './routes/candidate-pipeline'
import { Route as IndexRouteImport } from './routes/index'

const RecruitersRoute = RecruitersRouteImport.update({
  id: '/recruiters',
  path: '/recruiters',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionSummaryRoute = PositionSummaryRouteImport.update({
  id: '/position-summary',
  path: '/position-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyReportingRoute = DailyReportingRouteImport.update({
  id: '/daily-reporting',
  path: '/daily-reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatePipelineRoute = CandidatePipelineRouteImport.update({
  id: '/candidate-pipeline',
  path: '/candidate-pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidate-pipeline': typeof CandidatePipelineRoute
  '/daily-reporting': typeof DailyReportingRoute
  '/position-summary': typeof PositionSummaryRoute
  '/recruiters': typeof RecruitersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidate-pipeline': typeof CandidatePipelineRoute
  '/daily-reporting': typeof DailyReportingRoute
  '/position-summary': typeof PositionSummaryRoute
  '/recruiters': typeof RecruitersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidate-pipeline': typeof CandidatePipelineRoute
  '/daily-reporting': typeof DailyReportingRoute
  '/position-summary': typeof PositionSummaryRoute
  '/recruiters': typeof RecruitersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidate-pipeline'
    | '/daily-reporting'
    | '/position-summary'
    | '/recruiters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/candidate-pipeline'
    | '/daily-reporting'
    | '/position-summary'
    | '/recruiters'
  id:
    | '__root__'
    | '/'
    | '/candidate-pipeline'
    | '/daily-reporting'
    | '/position-summary'
    | '/recruiters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidatePipelineRoute: typeof CandidatePipelineRoute
  DailyReportingRoute: typeof DailyReportingRoute
  PositionSummaryRoute: typeof PositionSummaryRoute
  RecruitersRoute: typeof RecruitersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recruiters': {
      id: '/recruiters'
      path: '/recruiters'
      fullPath: '/recruiters'
      preLoaderRoute: typeof RecruitersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/position-summary': {
      id: '/position-summary'
      path: '/position-summary'
      fullPath: '/position-summary'
      preLoaderRoute: typeof PositionSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-reporting': {
      id: '/daily-reporting'
      path: '/daily-reporting'
      fullPath: '/daily-reporting'
      preLoaderRoute: typeof DailyReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate-pipeline': {
      id: '/candidate-pipeline'
      path: '/candidate-pipeline'
      fullPath: '/candidate-pipeline'
      preLoaderRoute: typeof CandidatePipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidatePipelineRoute: CandidatePipelineRoute,
  DailyReportingRoute: DailyReportingRoute,
  PositionSummaryRoute: PositionSummaryRoute,
  RecruitersRoute: RecruitersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
