/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamSummaryRouteImport } from './routes/team-summary'
import { Route as TargetsSetupRouteImport } from './routes/targets-setup'
import { Route as RecruitersRouteImport } from './routes/recruiters'
import { Route as PositionSummaryRouteImport } from './routes/position-summary'
import { Route as DailyReportingRouteImport } from './routes/daily-reporting'
import { Route as CandidatePipelineRouteImport } from './routes/candidate-pipeline'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecruiterIdRouteImport } from './routes/recruiter.$id'

const TeamSummaryRoute = TeamSummaryRouteImport.update({
  id: '/team-summary',
  path: '/team-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsSetupRoute = TargetsSetupRouteImport.update({
  id: '/targets-setup',
  path: '/targets-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitersRoute = RecruitersRouteImport.update({
  id: '/recruiters',
  path: '/recruiters',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionSummaryRoute = PositionSummaryRouteImport.update({
  id: '/position-summary',
  path: '/position-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyReportingRoute = DailyReportingRouteImport.update({
  id: '/daily-reporting',
  path: '/daily-reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatePipelineRoute = CandidatePipelineRouteImport.update({
  id: '/candidate-pipeline',
  path: '/candidate-pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterIdRoute = RecruiterIdRouteImport.update({
  id: '/recruiter/$id',
  path: '/recruiter/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidate-pipeline': typeof CandidatePipelineRoute
  '/daily-reporting': typeof DailyReportingRoute
  '/position-summary': typeof PositionSummaryRoute
  '/recruiters': typeof RecruitersRoute
  '/targets-setup': typeof TargetsSetupRoute
  '/team-summary': typeof TeamSummaryRoute
  '/recruiter/$id': typeof RecruiterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidate-pipeline': typeof CandidatePipelineRoute
  '/daily-reporting': typeof DailyReportingRoute
  '/position-summary': typeof PositionSummaryRoute
  '/recruiters': typeof RecruitersRoute
  '/targets-setup': typeof TargetsSetupRoute
  '/team-summary': typeof TeamSummaryRoute
  '/recruiter/$id': typeof RecruiterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidate-pipeline': typeof CandidatePipelineRoute
  '/daily-reporting': typeof DailyReportingRoute
  '/position-summary': typeof PositionSummaryRoute
  '/recruiters': typeof RecruitersRoute
  '/targets-setup': typeof TargetsSetupRoute
  '/team-summary': typeof TeamSummaryRoute
  '/recruiter/$id': typeof RecruiterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidate-pipeline'
    | '/daily-reporting'
    | '/position-summary'
    | '/recruiters'
    | '/targets-setup'
    | '/team-summary'
    | '/recruiter/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/candidate-pipeline'
    | '/daily-reporting'
    | '/position-summary'
    | '/recruiters'
    | '/targets-setup'
    | '/team-summary'
    | '/recruiter/$id'
  id:
    | '__root__'
    | '/'
    | '/candidate-pipeline'
    | '/daily-reporting'
    | '/position-summary'
    | '/recruiters'
    | '/targets-setup'
    | '/team-summary'
    | '/recruiter/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidatePipelineRoute: typeof CandidatePipelineRoute
  DailyReportingRoute: typeof DailyReportingRoute
  PositionSummaryRoute: typeof PositionSummaryRoute
  RecruitersRoute: typeof RecruitersRoute
  TargetsSetupRoute: typeof TargetsSetupRoute
  TeamSummaryRoute: typeof TeamSummaryRoute
  RecruiterIdRoute: typeof RecruiterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team-summary': {
      id: '/team-summary'
      path: '/team-summary'
      fullPath: '/team-summary'
      preLoaderRoute: typeof TeamSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets-setup': {
      id: '/targets-setup'
      path: '/targets-setup'
      fullPath: '/targets-setup'
      preLoaderRoute: typeof TargetsSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiters': {
      id: '/recruiters'
      path: '/recruiters'
      fullPath: '/recruiters'
      preLoaderRoute: typeof RecruitersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/position-summary': {
      id: '/position-summary'
      path: '/position-summary'
      fullPath: '/position-summary'
      preLoaderRoute: typeof PositionSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-reporting': {
      id: '/daily-reporting'
      path: '/daily-reporting'
      fullPath: '/daily-reporting'
      preLoaderRoute: typeof DailyReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate-pipeline': {
      id: '/candidate-pipeline'
      path: '/candidate-pipeline'
      fullPath: '/candidate-pipeline'
      preLoaderRoute: typeof CandidatePipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/$id': {
      id: '/recruiter/$id'
      path: '/recruiter/$id'
      fullPath: '/recruiter/$id'
      preLoaderRoute: typeof RecruiterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidatePipelineRoute: CandidatePipelineRoute,
  DailyReportingRoute: DailyReportingRoute,
  PositionSummaryRoute: PositionSummaryRoute,
  RecruitersRoute: RecruitersRoute,
  TargetsSetupRoute: TargetsSetupRoute,
  TeamSummaryRoute: TeamSummaryRoute,
  RecruiterIdRoute: RecruiterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
